block-list-secret-scan: []
branch: checkov
# check:
# - LOW
compact: false
download-external-modules: true
evaluate-variables: true
external-checks-dir:
- ./custom
external-modules-download-path: .external_modules
framework:
- all
mask: []
run-all-external-checks: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
check:
    - CCOE_AZ2_2
summary-position: bottom

#config file