block-list-secret-scan: []
branch: m
# check:
# - LOW
compact: false
download-external-modules: true
evaluate-variables: true
external-checks-dir:
- ./custom
external-modules-download-path: .external_modules
framework:
- all
mask: []
run-all-external-checks: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
check:
# - "CCOE_AZ2_TAGS_5"
    - "CCOE_AZ2_16"
summary-position: bottom

#config file
