metadata:
  name: "Deny the creation of private DNS"
  id: "CKV_AZURE_001"
  category: "Network"
  severity: "HIGH"
scope: 
  provider: "azure"
  block_type: "subcription" 
  # block_type: "resource"
definition:
  cond_type: "attribute"
  attribute: "subscription_id"
  operator: "not_equals"
  resource_types:
    - "azurerm_private_dns_zone"
  value:
    - "your"


        
# metadata:
#   name: "ensures app tag exists"
#   id: "CKV_AZURE_001"
#   category: "tagging"
#   severity: "HIGH"

# scope: 
#       provider: "azure" 
#      block_type: "resource"
# definition:
#     or:
#       - cond_type: "attribute"
#         attribute: "tags.app"
#         operator: "not_exists"
#         resource_types:
#             - "azurerm_virtual_machine_extension"
#             - "azurerm_monitor_smart_detector_alert_rule"
#             - "azurerm_monitor_action_group"
#             - "azurerm_security_center_automation"
#             - "azurerm_network_watcher"
#             - "azurerm_network_connection_monitor"
#             - "azurerm_network_watcher_flow_log"
#             - "azurerm_virtual_hub"
#             - "azurerm_management_group_template_deployment"
#             - "azurerm_resource_group_template_deployment"
#             - "azurerm_subscription_template_deployment"
#             - "azurerm_tenant_template_deployment"
#             - "azurerm_network_security_group"
#             - "azurerm_network_security_rule"
#             - "azurerm_automation_runbook"
#             - "azurerm_api_connection"
#             - "azurerm_role_assignment"
#             # - "azurerm_resource_group"
#       - cond_type: "attribute"
#         attribute: "tags.app"
#         operator: "exists"
        
# # the above code checks all actions from wrokflow if they have app tag or not


# # metadata:
# #   name: "Ensures app tag exists"
# #   id: "CKV_AZURE_001"
# #   category: "tagging"
# #   severity: "HIGH"
# #   description: "Ensure that specific tag values are used."
# # scope:
# #   provider: "azure"        
# #   block_type: "resource"   
# # definition:
# #     cond_type: "attribute"  
# #     attribute: "tags.app"   
# #     operator: "exists"     

  
#     #     - "azure_virtual_machine"
#     #     - "Microsoft.Compute/virtualMachines/extensions"
#     #     - "Microsoft.AlertsManagement/smartDetectorAlertRules"
#     #     - "microsoft.insights/actiongroups"
#     #     - "Microsoft.Security/automations"
#     #     - "Microsoft.Network/networkWatchers"
#     #     - "Microsoft.Network/networkWatchers/connectionMonitors"
#     #     - "Microsoft.Network/networkWatchers/flowLogs"
#     #     - "Microsoft.Network/networkWatchers/lenses"
#     #     - "Microsoft.Network/networkWatchers/pingMeshes"
#     #     - "Microsoft.Network/virtualHubs"
#     #     - "Microsoft.Resources/deployments"
#     #     - "Microsoft.ResourceGraph/queries"
#     #     - "Microsoft.OperationsManagement/solutions"
#     #     - "Microsoft.Network/networkSecurityGroups"
#     #     - "Microsoft.Automation/AutomationAccounts/Runbooks"
#     #     - "microsoft.web/connections"
    

  
