
# metadata:
#   name: "ensures app tag exists"
#   id: "CKV_AZURE_001"
#   category: "tagging"
#   severity: "HIGH"

# check:
#   scope: 
#     provider: "azure" 
# block_type: "resource"
# definition:
#     cond_type: "attribute"
#     attribute: "tags.app"
#     operator: "exists"
# the above code checks all actions from wrokflow if they have app tag or not


metadata:
  name: "Ensures app tag exists"
  id: "CKV_AZURE_001"
  category: "tagging"
  severity: "HIGH"
  description: "Ensure that specific tag values are used."
scope:
  provider: "azure"        
  block_type: "resource"   
definition:
    cond_type: "attribute"  
    attribute: "tags.app"   
    operator: "exists"     

  # and:
    # - cond_type: "filter"
    #   attribute: "resource_type"
    #   operator: "not_in"
    #   value:
    #     - "azure_virtual_machine"
    #     - "Microsoft.Compute/virtualMachines/extensions"
    #     - "Microsoft.AlertsManagement/smartDetectorAlertRules"
    #     - "microsoft.insights/actiongroups"
    #     - "Microsoft.Security/automations"
    #     - "Microsoft.Network/networkWatchers"
    #     - "Microsoft.Network/networkWatchers/connectionMonitors"
    #     - "Microsoft.Network/networkWatchers/flowLogs"
    #     - "Microsoft.Network/networkWatchers/lenses"
    #     - "Microsoft.Network/networkWatchers/pingMeshes"
    #     - "Microsoft.Network/virtualHubs"
    #     - "Microsoft.Resources/deployments"
    #     - "Microsoft.ResourceGraph/queries"
    #     - "Microsoft.OperationsManagement/solutions"
    #     - "Microsoft.Network/networkSecurityGroups"
    #     - "Microsoft.Automation/AutomationAccounts/Runbooks"
    #     - "microsoft.web/connections"
    

  
