# metadata:
#   name: "ensures app tag exists"
#   id: "Azure"
#   category: "tagging"
#   severity: "HIGH"

# check:
#   scope:
#     provider: "azure"
#     block_type: "resource"
#   definition:
#     - cond_type: "attribute"
#       attribute: "tags.app"
#       operator: "exists"



metadata:
  name: "Ensures app tag exists"
  id: "CKV_AZURE_001"
  category: "tagging"
  severity: "HIGH"
  description: "Ensure that specific tag values are used."


scope:
  provider: "azure"        # We're working with Azure resources
block_type: "resource"   # We're checking resource blocks in Terraform files
definition:
  - cond_type: "attribute"  # We're checking an attribute in the resource block
    attribute: "tags.app"   # We're verifying that "tags.app" exists
    operator: "exists"      # The operator is "exists" (the attribute must be present)


# metadata:
#   name: "Ensure snapshotlifetime tag exists. Valid Values are numbers from 0 to 30"
#   id: "CCOE_AZ2_2"
#   category: "tagging"
#   severity: "HIGH"
#   description: "Ensure that specific tag values are used."
# scope:
#   provider: "azure"
# block_type: "resource"
 
# definition:
#   and:
#     - cond_type: "attribute"
#       attribute: "tags.snapshotlifetime"
#       operator: "exists"
#     - cond_type: "attribute"
#       attribute: "tags.snapshotlifetime"
#       operator: "less_than_or_equal"
#       value: 30


  # and:
    # - cond_type: "filter"
    #   attribute: "resource_type"
    #   operator: "not_in"
    #   value:
    #     - "azure_virtual_machine"
    #     - "Microsoft.Compute/virtualMachines/extensions"
    #     - "Microsoft.AlertsManagement/smartDetectorAlertRules"
    #     - "microsoft.insights/actiongroups"
    #     - "Microsoft.Security/automations"
    #     - "Microsoft.Network/networkWatchers"
    #     - "Microsoft.Network/networkWatchers/connectionMonitors"
    #     - "Microsoft.Network/networkWatchers/flowLogs"
    #     - "Microsoft.Network/networkWatchers/lenses"
    #     - "Microsoft.Network/networkWatchers/pingMeshes"
    #     - "Microsoft.Network/virtualHubs"
    #     - "Microsoft.Resources/deployments"
    #     - "Microsoft.ResourceGraph/queries"
    #     - "Microsoft.OperationsManagement/solutions"
    #     - "Microsoft.Network/networkSecurityGroups"
    #     - "Microsoft.Automation/AutomationAccounts/Runbooks"
    #     - "microsoft.web/connections"
    

  
