metadata:
  name: "ensures app tag exists"
  id: "Azure"
  category: "tagging"
  severity: "HIGH"
scope:
  provider: "azure"
  block_type: "resource"  # This should be inside the scope block
definition:
  - cond_type: "attribute"
    attribute: "tags.app"
    operator: "exists"

  # and:
    # - cond_type: "filter"
    #   attribute: "resource_type"
    #   operator: "not_in"
    #   value:
    #     - "azure_virtual_machine"
    #     - "Microsoft.Compute/virtualMachines/extensions"
    #     - "Microsoft.AlertsManagement/smartDetectorAlertRules"
    #     - "microsoft.insights/actiongroups"
    #     - "Microsoft.Security/automations"
    #     - "Microsoft.Network/networkWatchers"
    #     - "Microsoft.Network/networkWatchers/connectionMonitors"
    #     - "Microsoft.Network/networkWatchers/flowLogs"
    #     - "Microsoft.Network/networkWatchers/lenses"
    #     - "Microsoft.Network/networkWatchers/pingMeshes"
    #     - "Microsoft.Network/virtualHubs"
    #     - "Microsoft.Resources/deployments"
    #     - "Microsoft.ResourceGraph/queries"
    #     - "Microsoft.OperationsManagement/solutions"
    #     - "Microsoft.Network/networkSecurityGroups"
    #     - "Microsoft.Automation/AutomationAccounts/Runbooks"
    #     - "microsoft.web/connections"
    

  
