name: Demo Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:  
  VAR: 'This is global'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
      - name: install pytest
        run: pip install pytest
      - name: run test
        run: pytest

  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: use of env
        run: echo "this is $VAR"
     
