# name: Terraform Security Checks

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout the repository
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       # Step 2: Set up Python
#       - name: Set up Python
#         uses: actions/setup-python@v4

     

#       # Step 3: Run Checkov with the correct path to the config
#       - name: Run Checkov
#         uses: bridgecrewio/checkov-action@master
#         with:
#            working-directory: '.'
#            config_file: ./checkov-config.yml

#           # file: ./rev.tf
         

#       # Optional: Install pytest if you intend to run additional tests
#       - name: Install pytest
#         run: pip install pytest



 
name: Terraform Security Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      # - name: Set up Python 3.8
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.8'  # Use any Python version you want

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies if you have a requirements file
      - name: setup python
        uses: actions/setup-python@v4
      - name: Verify Checkov Installation
        run: |
          checkov --version  # This will print the installed version of Checkov

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          file: ./main.tf
          config_file: ./checkov-config.yml
      - name: install pytest
        run: pip install pytest
     
 
