name: Terraform Security Checks

on:
  push:
    branches:
      - GCP-Datastream---Block-Public-Connectivity-Methods 
    paths: 
      - main.tf
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
             terraform_version: 1.11.4
             terraform_wrapper: false
      # - name: Install dependencies (if needed)
      #   run: |
      #     pip install -r requirements.txt || true  # Optional

      # - name: Run script
      #   run: |
      #     python p.py
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        
      # - name: Run Python script
      #   run: python p1.py
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          dir: ./
          config_file: ./checkov-config.yml
      
