name: Terraform Security Checks
on:
  push:
    branches:
    - 12-GCP-Disable-Hybrid-Cloud-IPv6-usage
    paths: 
    - main.tf
    - custom/checks.yml
    - custom/checks.py
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
             terraform_version: 1.11.4
             terraform_wrapper: false
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          dir: ./
          config_file: ./checkov-config.yml
      
