name: Terraform Security Checks

on:
  push:
    branches:
      - master
      - tag_cvlt_backup
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
      # - name: Install dependencies (if needed)
      #   run: |
      #     pip install -r requirements.txt || true  # Optional

      # - name: Run script
      #   run: |
      #     python p.py
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        
      # - name: Run Python script
      #   run: python p1.py
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          file: ./main.tf
          config_file: ./checkov-config.yml
      
