

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read  # Only read access to repository contents
  pull-requests: write  # Write access to pull requests (if needed)
  issues: write  # Write access to issues (if needed)
  actions: read  # Read access to actions (for workflows)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          file: ./workflow.yml
     
      - name: install pytest
        run: pip install pytest
      - name: run test
        run: pytest

 
